apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sNamespaceExists
spec:
  crd:
    spec:
      names:
        kind: K8sNamespaceExists
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            namespace:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sNamespaceExists
        
        violation[msg] {
          required := {namespace | namespace := input.parameters.namespace[_]}
          provided := {namespace | input.review.object.metadata.name[namespace]}
          result := provided - required
          count(result) == count(provided)
          msg := ("Tigera namespace is missing")
        }
