apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzurePodEnforceLabels
metadata:
  name: pod-enforce-labels
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["*"]
  parameters:
    namespace: {{ .Values.namespaces }}
