apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sclusterwidepolicy
spec:
  crd:
    spec:
      names:
        kind: K8sClusterWidePolicy
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sclusterwidepolicy
        
        name := input.review.object.metadata.name
        
        violation[msg] {
          contains(input.review.object.spec.namespaceSelector, "all()")
          msg := sprintf("Warning %s is a cluster-wide network policy", [name])
        }
